/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ARow: typeof import('@arco-design/web-vue')['Row']
    Piano: typeof import('./src/components/Piano.vue')['default']
    PianoLeft: typeof import('./src/components/PianoLeft.vue')['default']
    PianoRight: typeof import('./src/components/PianoRight.vue')['default']
    PitchPlayTester: typeof import('./src/components/PitchPlayTester.vue')['default']
  }
}
